### ISSUE TITLE
can't do ./gradlew runClient

### ISSUE THREAD

**Issue by BruzzTheHuzz0** [Katatje/ClientAPI#2]
I use the terminal and Sublime Text instead of an IDE, but anyway. There's a problem that my 4 months of java can't fix, and I'd appreciate some help! 
`./gradlew runClient
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-6084129e        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################
Version string '1' does not match SemVer specification 
You should try SemVer : http://semver.org/

> Task :compileJava
/Users/bryce/Desktop/ClientAPI-master/build/sources/main/java/cat/yoink/clientapi/Client.java:12: error: duplicate class: cat.yoink.example.Client
public class Client
       ^
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
5 actionable tasks: 3 executed, 2 up-to-date
`
Thanks for any help!

**Comment by Katatje** [comment]
Everything seems to work fine for me. Even from the command line. Have you made any changes to the source?

**Comment by BruzzTheHuzz0** [comment]
Sorry for the late response. I found the problem a while ago, it was that I deleted the example folder thinking it wasn't necessary. 

Overall great API! Do you have any plans to add a way to change settings in the GUI?

**Comment by Katatje** [comment]
Aight. I might in the future. I haven't worked on this in a while

**Comment by ezBot03** [comment]
Yeah me too, I wanna use this API but adding a way to change settings of modules in the GUI would be cool, it's pretty much an essential nowerdays.

**Comment by Katatje** [comment]
You can create your own settings. Read https://github.com/Katatje/ClientAPI#creating-a-module it shows you how

**Comment by ezBot03** [comment]
Are these editable in the ClickGUI in-game?

**Comment by Katatje** [comment]
You have to make your own ClickGUI for this. I might add an example in the future

**Comment by ezBot03** [comment]
Oh, alright.
